### ISSUE TITLE
从按钮看接口设计

### ISSUE THREAD

**Issue by nobodxbodon** [HL4A/hl4a-core#1]
从`间/安卓/视图/按钮`看到:
```
    @Override
    public void 置文本大小(Object $大小) {
        文本实现.置文本大小(this, $大小);
    }

    @Override
    public void 置文本颜色(Object $颜色) {
        文本实现.置文本颜色(this, $颜色);
    }
```
于是看`间.安卓.视图.实现.文本实现`确认允许的参数.

刚尝试如下:
```
$按钮.置文本颜色("绿色");
$按钮.置文本大小("30px");
```
在1.8.6中报错, 也许是版本不是最新? 用这个代码库在aide中编译后, 没找到IDE/build/bin下的apk(之前好像在那里).

话说回来, 上面的两个接口实在有些宽泛, 如果用重载也许会好些?
```
置文本大小(int $大小)
置文本大小(String $大小)
...
```
这样可以把运行时的问题提早到编译期发现.

另外, https://www.cs.cmu.edu/~charlie/courses/15-214/2014-fall/slides/17-api-design.pdf 提到

> Write client code before you implement the API 

个人觉得很有理, 这样可以从用户角度发现api设计的问题. 个人精力有限, 希望你也尽量写些小例子, 方便他人学习, 也可以对你的接口设计提早进行考验.

另外, 很多接口缺null检查 (这里提到: https://dzone.com/articles/the-java-8-api-design-principles)

`间.安卓.视图.实现.文本实现`如果不想用户使用, 最好接口不要public

最后推荐一本书: Effective Java. 上面链接里的有些就在书里(比如方法参数检查: ITEM 49: CHECK PARAMETERS FOR VALIDITY). 最新版好像是3. 惭愧个人也不是很通, 但之前的厂里用Java的reviewer时常在代码审核时用它参考.

**Comment by MikaGuraN** [comment]
置文本颜色 传入参数:

1. #FFFFFF格式
2. 默认自带类型 : 
基本(当前主题基本色)
深色(当前主题基本深色)
白色/黑色
3.使用 颜色.<颜色>.取基本色()等参数
你直接传了 绿色 这个字符串，是不能判断的
文本.置文本颜色(颜色.绿色.取基本色());这样

**Comment by MikaGuraN** [comment]
还有一种就是直接传颜色int
置文本颜色(0xffffff)

**Comment by MikaGuraN** [comment]
还有一点 google说 android上
布局大小使用dp而不是px
文本大小使用sp而不是px
(文本大小sp我做了处理，根据像素密度缩放，应该xml布局也会做缩放

**Comment by MikaGuraN** [comment]
null检查也是一个问题
很多方法我本来应该分成好几个同名方法
但是只做了一个参数为Object的方法，这样导致了用法不清晰

**Comment by MikaGuraN** [comment]
酷安上我最新的版本是1.8.10
不过这个视图参数检查在 间.安卓.工具.视图 这个类里
有 检查颜色 等等方法 很早之前就有了

**Comment by nobodxbodon** [comment]
> 重载的确有问题(其实我有点偷懒，因为改动interface就是很多视图要对应改)
很多方法我本来应该分成好几个同名方法
但是只做了一个参数为Object的方法，这样导致了用法不清晰

如果是纯重构的话, 方便的话能否把有这样情况的接口列一下(以及应该拆分出的方法). 我可以在电脑IDE里重构, 那样省工一些.

**Comment by MikaGuraN** [comment]
@nobodxbodon 视图类里的 检查图片 检查大小 检查输入类型 检查重力
用到这几个方法的大概都需要重构把....

**Comment by MikaGuraN** [comment]
@nobodxbodon 
根据你说的不能直接从颜色名称设置颜色我修改了一下
现在可以用 颜色#类型 的方式设置
比如 绿色#基本 而 基本 默认为主题颜色的基本

**Comment by MikaGuraN** [comment]
你要说从用户角度看api，我视图全都是代码写的，没有一个xml(笑哭)

**Comment by MikaGuraN** [comment]
其实我觉得这个重构没必要，要大量改动(特别多，有些重载了还是不清楚。
